# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "O mne"
  pageRef = "about-me"
  weight = 20

[[main]]
  name = "Webové publikovanie"
  pageRef = "series/wpub"
  weight = 30

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

# [[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/snp"
#  weight = 10

# [[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "SNP"
  pageRef = "series/snp"
  weight = 0

[[footer]]
  name = "DDSB"
  pre = 'sound'
  url = "https://matuspilnan.github.io/Dano-Drevo-Soundboard/"
  weight = 10

[[footer]]
  name = "Reďkovky"
  pageRef = "barjake-redkovky"
  weight = 20

[[footer]]
  name = "Koncerty"
  pageRef = "koncerty"
  weight = 30
