name: Build website

on:
  workflow_dispatch: 
  repository_dispatch:
    types: [obsidian-publish] 
  push:
      branches: master

jobs:
  import-obsidian-notes:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
        name: Checkout Obsidian vault
        with:
            repository: 'MatusPilnan/Knowledge'
            token: ${{ secrets.GH_PAT }}

      - name: Download Obsidian export
        run: |
          wget -c https://github.com/MatusPilnan/obsidian-export/releases/download/v25.2.1/obsidian-export-x86_64-unknown-linux-gnu.tar.xz
          tar -xf obsidian-export-x86_64-unknown-linux-gnu.tar.xz
          mv obsidian-export-x86_64-unknown-linux-gnu/obsidian-export ./obsidian-export

      - name: Create target directory
        run: mkdir -p ~/data/content

      - name: Run export
        run: ./obsidian-export . ~/data/content --only-tags publish --remove-tags publish

      - name: Fix escaped shortcodes
        run: |
          shopt -s globstar
          sed -i 's/{{\\</{{</g' ~/data/content/**/*.md

      - name: Upload exported notes
        uses: actions/upload-artifact@v4
        with:
            name: from-obsidian
            path: ~/data/content


  build:
    runs-on: ubuntu-22.04
    needs: import-obsidian-notes
    name: Build website
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            submodules: recursive
            
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.12
        with:
            hugo-version: '0.143.1'
            extended: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Download exported Obsidian content
        uses: actions/download-artifact@v4
        with:
            name: from-obsidian
            path: content

      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v6
            
      - name: Correct EXIF orientation
        run:  for filename in $(find content -name '*.jpg' -or -name '*.jpeg' -or -name '*.png'); do mogrify -auto-orient $filename; done;

      - name: Display structure of files
        run: tree content

      - name: Restore cached Resources
        id: cache-resources-restore
        uses: actions/cache/restore@v4
        with:
          path: resources/_gen
          key: ${{ runner.os }}-resources

      - name: Build site with Hugo
        run: hugo

      - name: Save Resources
        id: cache-resources-save
        uses: actions/cache/save@v4
        with:
          path: resources/_gen
          key: ${{ steps.cache-resources-restore.outputs.cache-primary-key }}
    
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
            path: public/

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

